// <auto-generated />
namespace BookTickets.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addcost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcost));
        
        string IMigrationMetadata.Id
        {
            get { return "201510091029455_add cost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
