// <auto-generated />
namespace BookTickets.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Person : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Person));
        
        string IMigrationMetadata.Id
        {
            get { return "201510071609049_Person"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
