// <auto-generated />
namespace BookTickets.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class isdeleted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(isdeleted));
        
        string IMigrationMetadata.Id
        {
            get { return "201510091111084_is deleted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
